name: Chatbot CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install pytest

      - name: Run tests
        continue-on-error: true 
        run: pytest main_test.py

      - name: Upload results
        if: always()
        run: |
          if [ -f summary.md ]; then
            cat summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No summary file found!" >> $GITHUB_STEP_SUMMARY
          fi