# Do not edit this file!

import pytest
import random
from main import fix_me

def test_fix_me():
    num1 = random.randint(1, 100)
    num2 = random.randint(1, 100)
    expected_ans = num1 + num2
    actual_ans = fix_me(num1, num2)
    
    is_correct = expected_ans == actual_ans
    
    if is_correct:
        with open("results.md", "w") as f:
            f.write("Your calculations passed! Good job!")
    else:
        with open("results.md", "w") as f:
            f.write("Uh oh! Looks like your logic is incorrect. Look over main.py\n")
            f.write(f"Expected results: **{expected_ans}**. Actual results: **{actual_ans}**")
    
    assert is_correct
        